### ISSUE TITLE
[Power Up]  Determining Efficient Multiplication Circuits via Brute Force

### ISSUE THREAD

**Issue by c0nrad** [XanaduAI/QHack2021#11]
### Team Name:

Sloppy Joe Pirates

### Project Description:

Introducing [mulbrute](https://github.com/c0nrad/mulbrute). mulbrute is a tool that brute forces over every possible combination of PauliX/CNOT/Toffoli in the attempt to find more efficient quantum multiplication circuits.

It includes a terminal UI ([blessed](https://github.com/jquast/blessed)) to track the progress of the brute forcing. Under the hood it uses [pennylane's qubit](https://pennylane.readthedocs.io/en/stable/code/api/pennylane.devices.default_qubit.html#module-pennylane.devices.default_qubit) simulator to validate the multiplication truth tables.

![mulbrute_1bit](https://user-images.githubusercontent.com/1901151/109031564-d8d3e400-7692-11eb-82cd-748b07710c2b.gif)

So far it's been able to determine two different 1bit multiplication [circuits](https://github.com/c0nrad/mulbrute#results-1bit-multiply).

### More details 

It turns out doing integer multiplication in quantum circuits is not as simple as one might guess.[1][2][3]. Multiplication requires a number of ancilla qubits that make it infeasible to use on real quantum computers today. But being able to multiply numbers is hugely important for a number of number theory problems (shor's), and math problems (hash cracking with grover's).

The goal of this project is to borrow a concept from computer security called "brute forcing" to see if we can construct a better multiplication circuit by randomly guessing. I'll start with 2bit multiplication and randomly construct circuits with a bunch of PauliX/CNOT/Toffoli's until they lineup with the correct multiplication table.

If successful I'll try to implement a simple hash function that uses multiplication (CRC) and then attempt to use Grover's to crack it! 

[1] https://www.quantamagazine.org/a-new-approach-to-multiplication-opens-the-door-to-better-quantum-computers-20190424/
[2] https://algassert.com/computer-science/2015/07/05/Things-I-Cant-Solve-Multiplication.html
[3] https://medium.com/@sashwat.anagolum/arithmetic-on-quantum-computers-multiplication-4482cdc2d83b

### Source code:

https://github.com/c0nrad/mulbrute

### Resource Estimate:

I'd like to try and brute force a 3qubit * 3qubit circuit. I'm not sure if anything will popout, but I'd like to leave a [m5.8xlarge](https://aws.amazon.com/ec2/pricing/on-demand/) live for 48 hours and let mulbrute run.

```
48hr * 1.536 ($/hr) = $73.73
```

For my project I am requesting $100.

**Comment by co9olguy** [comment]
Thanks for the submission @c0nrad! 

As a friendly tip, the more you can flesh out your resource estimate before the deadline, the better positioned you'll be to nab a power up :muscle:

**Comment by c0nrad** [comment]
Thanks @co9olguy, the powerup now includes a better resource estimation. If there's anything else I should add please let me know!

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @c0nrad!

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
