### ISSUE TITLE
[Power Up] Quantum Algorithms

### ISSUE THREAD

**Issue by anonymousr007** [XanaduAI/QHack2021#12]
### Team Name: 

anonymousr007

### Project Description: 

Repurpose all of the PennyLane demos and amazon-braket-pennylane-plugin to run on a quantum hardware device.
Write blogs on all Quantum Algorithms and it's application on medium.

### Source code: 

https://github.com/anonymousr007/quantum_algorithms

### Resource Estimate: 

1. https://pennylane.ai/qml/demonstrations.html
2. https://github.com/PennyLaneAI/PennyLane
3. https://github.com/aws/amazon-braket-sdk-python
4. https://github.com/aws/amazon-braket-pennylane-plugin-python
5. https://github.com/aws/amazon-braket-examples
6. https://indico.cern.ch/event/970903/ 
7. https://indico.cern.ch/event/970904/
8. https://indico.cern.ch/event/970905/
9. https://indico.cern.ch/event/970906/
10. https://indico.cern.ch/event/970907/
11. https://indico.cern.ch/event/970908/
12. https://indico.cern.ch/event/970909/

**Comment by co9olguy** [comment]
Thanks @anonymousr007!

Don't forget to fill out the Project Description and Resource Estimate portions of your entry before 12pm EST tomorrow. These will also be important for your eligibility for the Power Ups

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @anonymousr007!

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
