### ISSUE TITLE
[Power Up] Event classification with data-reuploading in High Energy Physics

### ISSUE THREAD

**Issue by togtim-aws** [XanaduAI/QHack2021#13]
**Team Name:** 

Entangled_Nets

**Project Description:**

The large experiments conducted in the field of particle physics require the detection and analysis of data produced in particle collisions that occurred using high-energy accelerators such as the LHC [2]. In these experiments, particles that are created by collisions are observed by layers of high-precision detectors surrounding the collision points, which produces large amounts of data about the collision. This motivated the use of "classical" machine learning techniques in different aspects to improve the performance and analysis of the data. Moreover, these developed techniques are also adapted to quantum computing, e.g, the unfolding measurement distributions via quantum annealing [3]. Intending to take advantage of both fields, the techniques in quantum machine learning, which are considered as one of the quantum computing algorithms that could bring quantum advantages over classical methods [4][5], will be used.

Furthermore, since the development of quantum hardware with a sufficient number of qubits is still in progress, circuits that make use of fewer qubits are more plausible to consider. Besides, such circuits may prove relevant even if they do not provide any quantum advantage, since they may be useful parts of larger circuits. We will use the idea of data reuploading discussed by Pérez-Salinas et al. [6], where it is shown that it's possible to load a single qubit with arbitrary dimensional data and then use it as a universal quantum classifier.

This project aims to use the method of data-reuploading, where qubits will be used as quantum classifiers to classify a certain dataset with high accuracy, and parametrized quantum circuit, whose variables are used to construct a cost function that should be minimized "classically". For our model, the SUSY dataset [1] will be considered.

[1] [SUSY Data Set - UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/SUSY#)

[2] [Event Classification with Quantum Machine Learning in High-Energy Physics](https://arxiv.org/abs/2002.09935)

[3] [Unfolding measurement distributions via quantum annealing](https://link.springer.com/article/10.1007/JHEP11(2019)128)

[4] [Quantum Computing in the NISQ era and beyond](https://quantum-journal.org/papers/q-2018-08-06-79/#)

[5] [Quantum Machine Learning in High Energy Physics](https://arxiv.org/abs/2005.08582)

[6] [Data re-uploading for a universal quantum classifier, Adrián Pérez-Salinas, Alba Cervera-Lierta, Elies Gil-Fuster, José I. Latorre](https://arxiv.org/abs/1907.02085)

**Source code:**

[The draft source code](https://github.com/VoicuTomut/Event-Classification-with-data-reuploading-in-High-Energy-Physics)

Note: This is a draft code for the initial entry for the AWS Power-up. The final source code will be modified and submitted next within the final deadline.

**Resource Estimate:**

We intend to use the power-up prize to further investigate the algorithms and try different approaches to increase the accuracy of our model using simulators. Besides testing the developed model on the quantum hardware access provided by AWS.

Aspen-8:
1 task x $0.30 / task = $0.30
Shots charges: 1,000 shots x $0.00035 / shot = $0.35 Total charges/Task: $0.65 = $0.30 + $0.35

1Qubit testing: Task charges:
Number of Tasks: 1000
Total charges: $650=1000x$0.65

2Qubits testing:
Number of Tasks: 1000
Total charges: $650=1000*$0.65

1 Qubit training:
Number of Tasks: 2001x0=20000 (10 epoch 200 tasks/epoch)
Total charges: $1300=2000x$0.65

2 Qubits training:
Number of Tasks: 200x10=20000 (10 epoch 200 tasks/epoch)
Total charges: $1300=2000$0.65

Total resource estimation for all objectives: $3900

**Comment by VoicuTomut** [comment]
**Resource estimation**
Aspen-8:
1 task x $0.30 / task = $0.30 
Shots charges: 1,000 shots x $0.00035 / shot = $0.35 Total charges/Task: $0.65 = $0.30 + $0.35 


1Qubit testing: Task charges: 
Number of Tasks: 1000 
Total charges: $650=1000x$0.65

2Qubits testing: 
Number of Tasks: 1000 
Total charges: $650=1000*$0.65

1 Qubit training: 
Number of Tasks: 2001x0=20000 (10 epoch 200 tasks/epoch) 
Total charges: $1300=2000x$0.65

2 Qubits training: 
Number of Tasks: 200x10=20000 (10 epoch 200 tasks/epoch)
 Total charges: $1300=2000$0.65

Total resource estimation for all objectives: $3900

**Comment by co9olguy** [comment]
Thanks for providing a detailed submission! :rocket:

**Comment by VoicuTomut** [comment]
Link to The draft source code : https://github.com/VoicuTomut/Event-Classification-with-data-reuploading-in-High-Energy-Physics

**Comment by co9olguy** [comment]
@T0gan Can you please clarify your team name exactly as it appears on the QML Challenges scoreboard? The name "Entangled_Nets" is not on there, but there are some close variations

**Comment by togtim-aws** [comment]
Hi @co9olguy, yes we had misspelled the team's name during registration. It is registered as "Entangeled_Nets". I've sent a clarification request to the Jury earlier, and they said that we can use the correct spelling during the open challenge submissions as long as the registered email account is active. Apologize for any inconvenience

**Comment by co9olguy** [comment]
Got it, thanks!

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @T0gan!

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
