### ISSUE TITLE
[Power Up] Continuous Variable QAOA 

### ISSUE THREAD

**Issue by ejdanderson** [XanaduAI/QHack2021#14]
### Team Name: 

Unfortunately, we're not Shor

### Project Description: 

We plan to fully understand and implement QAOA using Strawberry Fields to solve continuous optimization problems. We will follow the general strategy outlined in https://arxiv.org/pdf/1902.00409.pdf which demonstrates that QAOA can encode Grover's search over continuous spaces. This paper only tests the algorithm on a single numerical example, however we would like to run it across multiple examples to help benchmark its effectiveness.

### Source code: 

https://github.com/ejdanderson/continuous-qaoa

### Resource Estimate: 

We plan on implementing the algorithm in Strawberry Fields to simulate (and/or run on) a photonic CV quantum computer. However, we would use ideally use AWS to run the simulation and classical parameter tuning portion of the algorithm. Another route would also be to use other platforms qubit implementation approximates the CV degrees of freedom. 

https://arxiv.org/pdf/1902.00409.pdf

We have found numerous resources for optimization problems to target such as the ones found on this page https://www.sfu.ca/~ssurjano/optimization.html and plan to target the Powell and Colville functions, Colville being 4D where Powell is an n-dimensional.

@Jaybsoni @trentfridey

**Comment by co9olguy** [comment]
Thanks for the submission @ejdanderson :rocket: 

If possible, I would recommend fleshing out your resource estimate in a bit more detail before the deadline (this is an important criteria so it is good to be more specific/detailed about how you would use the AWS credits). You can take a look at some of the other teams' submissions for inspiration

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @ejdanderson !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
