### ISSUE TITLE
[Power Up] Performance Analysis of Tensor Network Ansaetze on Tensor Network Simulators, State Vector Simulators and Quantum Hardware.

### ISSUE THREAD

**Issue by shantomborah** [XanaduAI/QHack2021#15]
### Team Name: 

*The Racing Scarecrow*

### Project Description: 

*This Project aims to explore and benchmark the performance of tensor network simulators in training tensor network based ansaetze for discriminative and generative tasks. In particular, quantum circuit ansaetze based on Tree Tensor Networks (TTN) and Matrix Product States (MPS) are to be explored, as described in [this paper](https://arxiv.org/pdf/1803.11537.pdf). Two different versions of each of these ansaetze are to be considered, viz, the original model and a qubit frugal model based on qubit recycling.*

*For evaluating performance of the above mentioned ansaetze, [this dataset](https://www.kaggle.com/jsphyg/weather-dataset-rattle-package) is expected to be used for predicting rainfall in Australia. For generative models, the bars and stripes dataset is to be used. The same training algorithm is to be run on a Tensor Network Simulator, a State Vector Simulator and on Quantum Hardware and subsequently, run times and accuracy are to be compared.*

### Source code: 

*[Github Repo Link](https://github.com/Arkonaire/Tensor-Network-QML) - Work in Progress*

### Resource Estimate: 

*The following ansaetze are to be explored:*
* *TTN based Ansatz without qubit recycle.*
* *TTN based Ansatz with qubit recycle.*
* *MPS based Ansatz without qubit recycle.*
* *MPS based Ansatz with qubit recycle.*

*The following simulations are to be performed for each of the above ansaetze:*
* *At least one Tensor Network Simulator based training (Floq TPU / Braket TN1 Simulator, preferably both).*
* *Training on Braket SV1.*
* *Training on Braket Hardware (Aspen-9 / IonQ).*

*Projected future work after the hackathon:*
* *Explore Tensor Network based generative models.*
* *Explore more Tensor Network based ansaetze such as MERA and PEPS.*
* *Explore applications to dynamic simulations of 2D spin lattices.*

**Comment by co9olguy** [comment]
Thanks for the detailed submission @Arkonaire!

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @Arkonaire !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
