### ISSUE TITLE
[Power Up] Supervised learning with quantum enhanced feature spaces

### ISSUE THREAD

**Issue by RyanGale-AK** [XanaduAI/QHack2021#16]
### Project Description: 

We implement two classifiers on classical data that is mapped non-linearly onto a 2-qubit hilbert space.  The first classifier is a quantum variational classifier trained by stochastic gradient descent, this is followed with the implementation of a kernel based method.  Both models are great examples of the quantum advantage afforded by two canonical methods in QML.  

Our team is creating a Pennylane tutorial to showcase these implementations which are reproductions of the 2018 paper "Supervised learning with quantum enhanced feature spaces" by Havlicek et. al.  We are also extending the number of qubits used and increasing the circuit depth of these two models in order to investigate the presence of the barren plateau problem as described in McClean et. al. 2018.  The kernel method will be available for comparison to showcase the ability to avoid the barren plateau problem being a non-parametric method. 

### Source code: 

https://github.com/ryanhill1/QHack-2021

### Resource Estimate: 

We are increasing the depth of the QVC model to reproduce the barren plateau problem.  This will expectedly require a lot of processing capability, on the order of 20 qubits per layer at ~100 layers.  We are currently using SV1 for simulation but are also considering QPUs.

Each training evaluation will require roughly 96 tasks and 100,000 shots.  At $0.3 AWS credits per task and $0.00019 per shot, we estimate $47.8 AWS credits per training iteration.  Our experimentations will require some number of trials to reach ideal results as well as additional training and testing.  With an estimate of 50 trials of $47.8 per trial, we will need roughly $2390 AWS credits.

**Comment by co9olguy** [comment]
Thanks for the draft submission @RyanGale-AK :tada: 

As a tip to improve your chances of success, we will be looking carefully at the resource estimates when determining qualifying entries. The more specifics/details you can add here, the better your entry will be. Good luck!

**Comment by RyanGale-AK** [comment]
Thanks for the tip!

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @RyanGale-AK !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
