### ISSUE TITLE
[Power Up] [submission] Quantum-Aided Medical Image Diagnosis

### ISSUE THREAD

**Issue by techwithshadab** [XanaduAI/QHack2021#18]
### Team Name: 

*qt*

### Project Description: 

<h3> Quantum-Aided Medical Image Diagnosis </h3>

<p align="center" width="400">
  <img src="https://github.com/shadab-entrepreneur/QuantumComputing/blob/main/QHack-2021/images/IDC.png?raw=true"  />
</p>

#### Objective
Invasive ductal carcinoma (IDC) is - with ~ 80 % of cases - one of the most common types of breast cancer. It's malicious and able to form metastases which makes it especially dangerous. Often a biopsy is done to remove small tissue samples. Then a pathologist has to decide whether a patient has IDC, another type of breast cancer, or is healthy. In addition, sick cells need to be located to find out how advanced the disease is and which grade should be assigned. This has to be done manually and is a time-consuming process. Furthermore, the decision depends on the expertise of the pathologist and his or her equipment. Here, I'm proposing to use <b> Quantum Genetic Algorithm (QGA) </b> and <b> Support Vector Machines (SVMs)</b>. I hope this method will be having effective results when compared to some of the standard approaches. This way one would be able to overcome the dependence on the pathologist which would be especially useful in regions where no experts are available.
Also, after classifying images using QGA and SVMs, I will use <b>Quanvolutional Neural Networks (QNN)</b> or a <b>hybrid quantum-classical model</b> which can have the advantage over the classical approach and make a comparative analysis with standard approaches like Convolutional Neural Networks (CNN)
*Note*- Finally testing this approach on different Quantum Devices and Simulators and come up with final results.

#### Context
Invasive Ductal Carcinoma (IDC) is the most common subtype of all breast cancers. To assign an aggressiveness grade to a whole mount sample, pathologists typically focus on the regions which contain the IDC. As a result, one of the common pre-processing steps for automatic aggressiveness grading is to delineate the exact regions of IDC inside of a whole-mount slide.

#### Content
The original dataset consisted of 162 whole mount slide images of Breast Cancer (BCa) specimens scanned at 40x. From that, 277,524 patches of size 50 x 50 were extracted (198,738 IDC negative and 78,786 IDC positive). Each patch’s file name is of the format: uxXyYclassC.png — > example 10253idx5x1351y1101class0.png. Where u is the patient ID (10253idx5), X is the x-coordinate of where this patch was cropped from, Y is the y-coordinate of where this patch was cropped from, and C indicates the class where 0 is non-IDC and 1 is IDC.

### Source code: 

*[Code](https://github.com/shadab-entrepreneur/QuantumComputing/edit/main/QHack-2021/Open%20Hack/)*

### References:
- https://www.researchgate.net/publication/342391570_Quantum_neural_network_for_quicker_clinical_prognostic_analysis_An_application_and_experimental_study_using_CT_scan_images_of_COVID-19_patients
- https://deepai.org/publication/quantum-medical-imaging-algorithms
- https://link.springer.com/article/10.1007/s00521-020-05518-x
- https://arxiv.org/abs/2011.02831
- https://pennylane.ai/qml/demos/tutorial_quanvolution.html
- https://pennylane.ai/qml/demos/tutorial_multiclass_classification.html

### Resource Estimate: 
We intend to use the power-up prize to further investigate the algorithms and try different approaches to increase the accuracy of our model using simulators and quantum hardware provided by AWS

Original Dataset Size- 278k
Number of records going to consider in the base model- 5k
Number of Shots- 500
Number of iterations- 2 or 3

#### Cost Estimation:
Rough Cost breakup of 250USD (got as being in top 40 team) + 4000USD (POWER UP if given)
| Hardware | Estimated Cost |
| ------- | ------- |
| D-Wave | $950 = 5000 * 500 * 2 * 0.00019 |
| Rigetti | $2625 = 5000 * 500 * 3 * 0.00035 |
| Simulation | $675 |

First design and test the model on the simulator, for which I'm taking a rough estimation of around $650+, after that run the code on Quantum Devices to get actual results and compare results. 
*Note*- This is just a rough estimate, actual cost may increase/decrease based on the usage

### Future Work:
I'm pursuing my MS, so I will take forward this research as my final dissertation and will:
- Develop a novel Quantum Algorithm that can be used for medical image diagnosis and test the results with different datasets available publicly
- Optimize the circuit and see which approach works better with which set of datasets and circuit combination
- Design API and web app to provide services in healthcare image analysis

**Comment by co9olguy** [comment]
Thanks so much for the draft submission @shadab-entrepreneur! :ok: 

Make sure to include a detailed resource estimate before the 12pm EST deadline. It is an important criteria for us when evaluating submissions

**Comment by techwithshadab** [comment]
Thanks @co9olguy, I have given a rough estimate but it might vary based on the actual implementation

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @shadab-entrepreneur !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
