### ISSUE TITLE
[Power Up] Sound Classification using Quanvolutional Neural Networks

### ISSUE THREAD

**Issue by heba0** [XanaduAI/QHack2021#21]
### Team Name: 

Two Bits in a Box

### Project Description: 

Sound classification is one of the popular topics in the classical machine learning literature eg.[[1](https://ieeexplore.ieee.org/document/8648629)],[[2](https://ieeexplore.ieee.org/document/8635051)]. One of the used methods is applying CNN to the spectrograms of the sound samples. Nevertheless, we couldn't find similar applications in the Quantum Machine Learning literature.

In this project we aim to use [Quanvolutional Neural Networks](https://pennylane.ai/qml/demos/tutorial_quanvolution.html) to classify sound using [this kaggle dataset](https://www.kaggle.com/c/freesound-audio-tagging/data?select=train.csv). We will mainly compare the performance of the Quanvolutional Neural Networks to the equivalent classical CNN implementation, and explore techniques in the Quantum Machine Learning literature that can enhance the existing classical ML techniques.

### Source code: 

https://github.com/heba0/Sound-Classification-using-Quanvolutional-Neural-Networks

### Resource Estimate: 

The AWS credit will help us experiment better with Quantum Computing resources. 
Our model will use around 3 layers with 3x3 kernels -> 3x3x3 = 27 qubits per task
We would like to use the Rigetti  with 2000 shots 
The training and testing datasets have around 9700 samples (can be sampled to smaller datasets)

Our Estimation is:
Training Sample = 0.3x400 + 0.3x400 
Testing Sample = 0.3x400 
Shots = 0.00035x10000
Total = $903.5

### References: 

[1] [Jaiswal, K. and Kalpeshbhai Patel, D., 2018. Sound Classification Using Convolutional Neural Networks. 2018 IEEE International Conference on Cloud Computing in Emerging Markets (CCEM),.
](https://ieeexplore.ieee.org/document/8648629)
[2] [Davis, N. and Suresh, K., 2018. Environmental Sound Classification Using Deep Convolutional Neural Networks and Data Augmentation. 2018 IEEE Recent Advances in Intelligent Computational Systems (RAICS),.](https://ieeexplore.ieee.org/document/8635051)

**Comment by co9olguy** [comment]
Thanks for the draft submission @heba0! 

Make sure to update your proposal before the deadline with a detailed resource estimate! This is an important category for us to determine a project's eligibility for those Power Up credits. The more details you can provide about how you will specifically leverage those credits for the project, the better :muscle:

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @heba0 !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
