### ISSUE TITLE
[Power Up] Towards Quantum Self-Improvement

### ISSUE THREAD

**Issue by Shangjie-Guo** [XanaduAI/QHack2021#23]
### Team Name: 

Finq

### Project Description: 

Self-improvement describes an agent that can improve its own performance recursively. Inspired by this concept, we propose to examine an iterative setup, quantum self-improvement (QSI), which consists of (1) optimizing gate fidelity of a noisy quantum computer (NQC) with the variational quantum gate optimization algorithm (VQGO, https://arxiv.org/abs/1810.12745) running on the NQC itself, and (2) replacing the previous NQC gate used in VQGO with the optimized one. By repeating step (1) and (2), we may enhance both the hardware and the algorithm. Here, we demonstrated the feasibility of QSI by optimizing the CNOT gate. Our goal is to validate QSI on a physical NQC. 

Meanwhile, we noticed that the originally proposed VQGO is not compatible with NQC due to erroneous random state sampling. Therefore, we improved VQGO’s noise robustness by updating the reference state with a few-shot estimation of the prepared one, see draft details [here](https://github.com/Shangjie-Guo/Quantum-Self-Improvement/blob/main/Improve_VQGO_explained.pdf).

### Source code: 

https://github.com/Shangjie-Guo/Quantum-Self-Improvement

### Resource Estimate: 

As Floq provides free simulator access, we only need to spend resources on testing the final result on the real quantum device (Regitti Aspen-9). We will run our two-qubit circuits parallelly on directly connected qubits to do 15 Experiments per Run. For our current setting, we estimate:

Optimization steps / Run = 10-100
Cost function evaluations / Optimization step = 5
State estimations / Cost function evaluation  = 10-30
Shots / State estimation = 6 * (10-100)

That gives us 10^4 - 10^7 shots per run, and we need to do more tests on how much accuracy we need to have a more accurate estimation. The reward ($4,000) will allow us to do ~10^7 shots on Aspen 9, which can cover our highest estimation. Meanwhile, we are investigating direct fidelity estimation (https://arxiv.org/abs/1104.4695) and other possible settings, which may reduce Shots / State estimation number. 

### Milestones:

✅      Implement VQGO with pennylane for CNOT gate
✅      Improve VQGO compatibility for noisy random state sampling
✅      Validate QSI
✅      Integrate QSI into VQGO cycles
🔜      Upgrade to direct fidelity measurement
🔜      Broadcast two qubit circuit for large scale device use, include Floq and Aspen-9
🔜      Sanity check with some different noise models on Floq 
🔜      Test VQGO & QSI on Aspen-9! 💸

**Comment by co9olguy** [comment]
Thanks for the draft submission @Shangjie-Guo! :+1: 

Your resource estimate is a great start! The more details you could provide us before the deadline about how you expect those credits to translate into device usage, the better it helps us judge the submission. Good luck!

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @Shangjie-Guo !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
