### ISSUE TITLE
[Power Up] Quantum Recommendation Systems

### ISSUE THREAD

**Issue by MyEntangled** [XanaduAI/QHack2021#24]
### Team Name: 

QCal

### Project Description: 

**Goal**: Implement [Quantum Recommendation Systems](https://arxiv.org/abs/1603.08675)

Quamtum Recommendation Systems (QRS) is the first algorithm for recommendation systems with polylogarithmic runtime with respect to the preference matrix dimension. Although it inspired the birth of a classical algorithm of similar complexity, the quantum algorithm still serves as an example for use of quantum machine learning algorithms in real-world problems.

Provided an m x n preference matrix assumed to have a good rank-k approximation, QRS utilizes a quantum routine called phase estimation to sample from the subspace spanned by  singular vectors corresponding to major singular values. With high probability, this strategy can recommend relevant items to a user given his/her partial preference.

### Source code: 

https://github.com/MyEntangled/Quantum-Recommendation-System

### Resource Estimate: 

We would like to experiment the algorithm with different configurations, for example, with physical backends provided by AWS Braket, e.g. superconducting qubits, ion traps, and quantum annealing. We also aim to expand the project to different encoding schemes and optimization techniques, which Pennylane-Braket plugin is of great help.

**Comment by co9olguy** [comment]
Thanks for the draft submission @MyEntangled! :tada: 

As a tip, we will be taking the Resource Estimate section under strong consideration when assessing the eligible submissions. The more fine-grained details you could provide about how the credits will be specifically used for your project, the better we can gauge the project.

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @MyEntangled !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
