### ISSUE TITLE
[Power Up] Trainable Quantum Kernels with PennyLane

### ISSUE THREAD

**Issue by emgilfuster** [XanaduAI/QHack2021#25]
### Team Name: 

Notorious FUB

### Project Description: 

A central bottleneck of kernel-based machine learning is the choice of the kernel itself. This problem, called model selection, saw some novel approaches in the 2000s, where a couple quantities were proposed as kernel quality estimators. It was proved that a kernel who had a high polarization or alignment would have good classification and generalisation behavior. One would use this instead of an exhaustive parameter search e.g. when choosing the value of the variance for the everpresent gaussian kernels.

Recent research efforts have been made in studying the use and performance of quantum kernels in learning models. We propose to leverage the theoretical results from those early papers into studying the viability of trainable quantum kernels. We attempt this under the lens of the full-stack, providing a general purpose new module to Pennylane for further implementation of kernel methods. This includes methods e.g. for dealing with noise in the kernel matrix estimation, and for maximizing the kernel alignment, out of the shelf.

### Source code: 

https://github.com/thubregtsen/qhack

https://github.com/thubregtsen/qhack/tree/master/wp_TK

https://github.com/PennyLaneAI/pennylane/pull/1102

### Resource Estimate: 

The pipeline we have defined includes three steps: optimizing a few variational parameters, training an SVM, and using the support vectors to predict the value of unseen data. We will have to then repeat this process for several datasets.

After testing data sets of different sizes and predicting the effect of the size in the number of circuit evaluations required for the three steps of training, we have concluded we need 9 datasets and 3000 circuit evaluations of 400 shots each. This amounts to roughly $420 per dataset on Rigetti's devices, so $3780 in total. Including test runs to ensure the viability of the entire pipeline this should be raised to $4000. Because of this we would greatly benefit from the PowerUp, as it would enable us to implement our pipeline in a realistic setting.

**Comment by co9olguy** [comment]
Thanks for the draft submission @emgilfuster!

Thanks as well for providing a detailed costing of the resource estimate. These kind of specifics are very helpful for us when assessing the submissions.

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @emgilfuster !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
