### ISSUE TITLE
Beam Bending Simulation

### ISSUE THREAD

**Issue by Qudsiaamir** [XanaduAI/QHack2021#33]
### Team Name:
 
Quantumalpha

### Project Description: 

The simulation of mechanical systems requires PDE which is a costly function when the dimensions are increased, FEM is used to simulate the system. we can use the differentiation and gradient findings to make it better.

### Source code: 

https://github.com/Qudsiaamir/Qhack.git

### Resource Estimate: 

Recent interest shows that Quantum Computing can speed up thing for FEA.
Mostly we are more focused on finding better ways to solve the problem the extra credit can help us build better scale solutions with lot of trails.

**Comment by glassnotes** [comment]
Hi @Qudsiaamir , thanks for the draft submission!

The Resource Estimate is a very important criteria when we are considering the eligibility of entries. If possible, I would recommend fleshing this out in much more detail. You can take a look at some of the other entries for guidance on how to build this.

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @Qudsiaamir !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
