### ISSUE TITLE
[Power Up] Geflo

### ISSUE THREAD

**Issue by moskalyk** [XanaduAI/QHack2021#34]
### Team Name: 

geflo

### Project Description: 

geflo is a program & cli to aid those in decentralized cognitive research. It consists of 2 main components:
1) Model: a multi class variational classifier to categorize fNIRS brain headset data from 3 different session variants 
2) Market: saves the weights to be transferred to perform model tuning on additional private datasets, a type of transfer learning

The cli gives a user the ability to interact with models by purchasing those that are pre-trained from a market stored on the blockchain, possibly mix in pricing in the future.

With these 2 pieces: computation & parameter sharing, the hope is that this pipeline can be applied to various different use cases that require a pre-trained model of cognitive data (e.g. chemistry, etc.)

### Source code: 

https://github.com/deep6org/geflo

### Resource Estimate: 
The hypothesis is if you're analyzing a wave with multiple underlying frequencies, you want to be able to do so in many ways. Currently the project uses 3 qubits to learn on 3 energy bins and takes over 20 minutes per iteration to train on a local simulator. The team would like to be able to run such circuit on a remote device to decrease the time of training & development.

**Comment by glassnotes** [comment]
Hi @moskalyk  , thanks for the draft submission!

The Resource Estimate is a very important criteria when we are considering the eligibility of entries. If possible, I would recommend fleshing this out in much more detail. You can take a look at some of the other entries for guidance on how to build this.

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @moskalyk !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
