### ISSUE TITLE
Investigating the effects of quantum layers in machine learning by building a custom PennyLane wrapper. 

### ISSUE THREAD

**Issue by SaadNaeem96** [XanaduAI/QHack2021#35]
### Team Name: 
Cabriella

### Project Description: 

Here we investigate how does making a machine learning include quantum layers effect machine learning results. To do this, we employ a custom made python library which integrates PennyLane with python. 

The aim of this library is to make quantum machine learning easier to do by removing the need to encode hardware such as circuit, device, QNode etc, where our library atomically customizes according to input. We do this from the motivation that why classical machine learning get to not think about hardware, whereas quantum machine learners do. 

Equipped with this library, we will be able to efficiently test different types of quantum models to understand how the results are effected.  

### Source code: 
*A hyperlink to the draft source code for your team's hackathon project (e.g., a GitHub repo).*
https://github.com/SaadNaeem96/QHack-2021-by-XanaduAI/tree/main/Hackathon

### Resource Estimate: 

The method suggested includes 1) Making the python library 2) Investigating how qunautm layers chage a classical machine learning result.

Our usage of resources will include:
1) We have decided that the for 1) we will study 500 circuits existig kinds of circuits for each type of quantum machine learning model (CNN, ANN, Decision tree, LSTM etc)
2) Testing the results of 2000 different types of classical machine learning result by adding variable number of qunautm machine learning  layers/nodes. 

We intend to use the power-up prize to further investigate the algorithms and try different approaches to increase the accuracy of our model using simulators and quantum hardware provided by AWS. 

1. A Tensor Network Simulator based training (Floq TPU / Brakcet TN1 Simulator).
2. Training on Bracket SV1

**Comment by SaadNaeem96** [comment]
> _Your team's name (matching the name used on the QML Challenge Scoreboard)_

Cabriella

**Comment by glassnotes** [comment]
Hi , thanks for the draft submission! It looks like you are still editing, so just want to remind you to update the project title in the issue name while you are completing the remaining portions of the template.

**Comment by SaadNaeem96** [comment]
Qudsiaamir? They are not a participant in this project. 
And yes we have change everything. Does it seem alright now?

**Comment by glassnotes** [comment]
> Qudsiaamir? They are not a participant in this project.
> And yes we have change everything. Does it seem alright now?

Sorry that was my bad, I tagged the wrong user. Yes, you are good to go :smiley:

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @SaadNaeem96 !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
