### ISSUE TITLE
[Power Up] Quantum Spectral Graph Convolutional Neural Networks 

### ISSUE THREAD

**Issue by DanielPolatajko** [XanaduAI/QHack2021#36]
### Team Name: 

QUACKQUACKQUACK

### Project Description: 

Over recent years, a large influx of interest has been observed in classical machine learning regarding the research into and usage of Graph Neural Networks (GNN).  Part of the reason for this interest is due to their innate ability to model vast physical phenomena through the medium of pair-wise interactions between the elements of the systems. Similarly , interest in Quantum Machine Learning models is also increasing, as such architectures can leverage the computational efficiency of quantum computers and offer problem tailored solutions by [handcrafting antsatze guided by physical interactions](https://arxiv.org/abs/2006.11287). Consequently, we believe that combining these separate ideas will offer mutual benefits and improve model performance and advanced research in both fields. Seeing how GNNs are used to solve combinatorial tasks [Combinatorial optimisation and reasoning with graph neural networks by Cappart et al](https://arxiv.org/abs/2102.09544) included in workshops such as [“Deep Learning and Combinatorial Optimisation” help at IPAM UCLA](https://www.ipam.ucla.edu/programs/workshops/deep-learning-and-combinatorial-optimization/)., we would argue that it is the right time to start thinking more about Quantum Graph Neural Networks (QGNN). 

We propose to implement Quantum Spectral Graph Convolutional Neural Networks (QSGCNN) as described in [Verdon et al.](https://arxiv.org/abs/1909.12264). We are planning to use the [Pennylane documentation on Quantum Graph Recurrent Neural Networks (QGRNNs)](https://pennylane.ai/qml/demos/qgrnn.html) as a guideline, and we will replace the RNN layer with a spectral convolutional layer. In particular, we want to perform unsupervised graph clustering as described in [Verdon et al.](https://arxiv.org/abs/1909.12264). We specifically want to compare the performance and inference speed between classical GNN models and their quantum counterparts on simple datasets, such as the one in [Verdon et al.](https://arxiv.org/abs/1909.12264) or k-core distilled popular GNN benchmark datasets (e.g. Cora, or Citeseer). This would primarily include the most popular and basic models based on the SGCNNs and as a stretch goal also on GraphSAGE. The results would be then compared with standard graph partitioning algorithms.

### Source code: 

https://github.com/bossemel/QHack_Project/tree/main

### Resource Estimate: 

We expect that the clustering performed by these models on these very small datasets won’t be insightful enough. Therefore, in order to obtain meaningful results from this experiment, we will need to train quantum models on graphs with a reasonable number of vertices and edges. We observe that the number of qubits required in the ansatz for QGNNs scales linearly with the number of vertices of the graph, and consequently it would be infeasible for us to demonstrate a meaningful application of the QGSCNN without using either a high-tech simulator, or by using an actual quantum device. Therefore, while we are unable to provide explicit costing projections at this time, we can say with certainty that having access to AWS credits will allow us to produce a much more impactful project on this topic.

**Comment by glassnotes** [comment]
@DanielPolatajko thank you for your draft submission!

**Comment by DanielPolatajko** [comment]
Just to clarify for the judges, I erroneously wrote our name as QUACK QUACK QUACK in the original edit of the issue, but in fact our team is called QUACKQUACKQUACK, and a teammate pointed out to me that teams with both names exist, so I wanted to avoid any confusion. I've edited the issue to have the correct team name. Thanks!

**Comment by co9olguy** [comment]
@DanielPolatajko thanks for the info

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @DanielPolatajko !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
