### ISSUE TITLE
Facing problem of reading value of Quantum_gradient_100_template 1.in file

### ISSUE THREAD

**Issue by ashishpatel26** [XanaduAI/QHack2021#4]
1,0.5,-0.765S0.1,0,-0.654

This value is unable to read by `sys.stdin.read()` it's return blank. Any help.

**Comment by josh146** [comment]
Hi @ashishpatel26, what command are you using to read in this value? Are you using the command provided in the [how-to guide](https://github.com/PennyLaneAI/pennylane-cirq/pull/51)?

**Comment by huckiyang** [comment]
@ashishpatel26 Did you feed the `1.in` together?

You can test by

```python
python quantum_gradients_100_template.py < 1.in
```

and check the grounded answer by
```python
cat 1.ans
```
