### ISSUE TITLE
[Power Up] Analysis, Prediction and Evaluation of Covid-19 Datasets using Quanvolutional Neural Network

### ISSUE THREAD

**Issue by pinaki-sen** [XanaduAI/QHack2021#41]
### Team Name: 

QTechnocrats

#### Dataset used -
We have used [this datset](https://www.kaggle.com/pranavraikokte/covid19-image-dataset) from Kaggle which contains 250 training and 65 testing images for our model.

#### Our Approach to the classifier Model-
Images given in the dataset are real life chest x-rays and are not previouly modified. So all have different dimensions. So we reduced the all the image size to a specific dimension. It would be more convenient to fix the image size to 256x256 but due to limitations of computational resources we have reduced it to 28x28 size. 

#### Applying Quanvolutional Layer-
We have extended the single layer approach of Quanvolutional Neural Network from here to multiple layers, to be exact 4 layers in our model.
Initially Each images has the dimension of (28x28x1) which is fed to the first Quanvolutional layer and converted to (14x14x4). The 2nd Layer converts it to (7x7x16), 3rd layer to (3x3x64) and finally the 4th and last layer converts each to a (1x1x256) dimensional data matrix.
![alt text](https://github.com/QTechnocrats/covid19-detection-chest-xray-dataset/raw/main/images/qnn.png?raw=true)

#### Classifier Model-
After the Quanvolutional layers, we have the classifier model. The classifier model consists of two subclassifiers each of which is a binary classifier. We dente those two by 'Model-1' and 'Model-2'.

Model-1 classifies between two classes - 'Normal Person' and 'Covid19/Viral Pnemonia'.
Model-2 classifies between two classes - 'Covid10' and 'Viral Pneumonia'.

![alt text](https://github.com/QTechnocrats/covid19-detection-chest-xray-dataset/raw/main/images/models.png)

#### Prediction - 
While Predicting, we first give input to the Model-1. If it predicts as Normal person, then it is the final prediction assigned to the input. If not, then we give the same input to Model-2 and it finally predicts whether the chest x-ray is Covid19 patient or Viral Pneumonia patient.

#### Reference - 
1. Saad Albawi, Tareq Abed Mohammed, and Saad Al-Zawi, "Understanding of a convolutional neural network, In 2017 International Conference on Engineering and Technology (ICET), pages 1-6. IEEE, 2017.
2. Maxwell Henderson, Samriddhi Shakya, Shashindra Pradhan, and Tristan Cook.
"Quanvolutional neural networks: powering image recognition with quantum circuits",
Quantum Machine Intelligence, 2(1):19, 2020.
3.Junhua Liu, Kwan Hui Lim, Kristin L Wood, Wei Huang, Chu Guo, and He-Liang Huang, "Hybrid quantum-classical convolutional neural networks",
arXiv preprint arXiv:1911.02998, 2019.
4. Quanvolutional Neural Networks.
https://pennylane.ai/qml/demos/tutorial_quanvolution.html.

### Source code: 

Here is the [Presentation](https://github.com/QTechnocrats/covid19-detection-chest-xray-dataset/blob/main/Presentation.pdf) of Overall Project. 
This [ReadMe](https://github.com/QTechnocrats/covid19-detection-chest-xray-dataset/blob/main/README.md) fille consists of the total description of project. 
Here you can access the [source code](https://github.com/QTechnocrats/covid19-detection-chest-xray-dataset)

### Resource Estimate: 

For training of each images,
No. of times circuits are called  = 
 (shots assigned to the device * number of training images * number of iteration)

Now if we set shots=1024, training images  = 250 and iteration=50, 
we will be calling a Quantum circuit 12800000 times for each model training. 
we have two models to train. So total 25600000 times circuit will be called. 

Also better accuracy will be achieved with larger dataset, which demands more computational resources. 
Although here the parameters of Quanvolutional layers are not trained. If those has to be trained, that will add more circuit calls.

**Comment by glassnotes** [comment]
Thanks for the submission @senpinaki222 !

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @senpinaki222 !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
