### ISSUE TITLE
[Power Up] DQN with Quantum Variational Circuits

### ISSUE THREAD

**Issue by carlosamds** [XanaduAI/QHack2021#43]
### Team Name: 
DAC

### Project Description: 
The algorithm implements the pseudocode described by [Reinfocement Learning With Quantum Variational Circuits](https://arxiv.org/pdf/2008.07524.pdf) of a reinforcement learning algorithm based on quantum DNN, more specifically DQN. The network architecture is the same as the one used in the paper, and the algorithm follows the classical DNN structure, based on PennyLane to build and measure our qubits.
The training is made in the BlackJack environment for simplicity, but we would like to extend that to more challenging environments.

### Source code: 
https://github.com/carlosamds/qhack-dac

### Resource Estimate: 
If awarded with the additional AWS credits we intend to make many more tests regarding the circuit architecture and try harder gym enviroments. Using the Amazon Braket services, more of those tests would be possible and they could be finished much quicker.

**Comment by glassnotes** [comment]
Hi @carlosamds thank you for the submission!

**Comment by huckiyang** [comment]
Hello @carlosamds 

Just want to share that the work of "[Reinforcement Learning With Quantum Variational Circuits](https://arxiv.org/pdf/2008.07524.pdf)" kindly states that 

```
... We take inspiration from and extend the work done in [10] to use Quan-tum Variational Circuits (QVC), ...
```

10. [Variational Quantum Circuits for Deep Reinforcement Learning](https://arxiv.org/pdf/1907.00397.pdf)

We are the authors of this work [10] and provided an open-source GitHub repo [here](https://github.com/ycchen1989/Var-QuantumCircuits-DeepRL), which may also fit your interests. Also thanks [Xanadu AI Software Competition Research](https://medium.com/xanaduai/xanadu-software-competition-the-results-are-in-9ccb6a3b591b) Track in 2019.

Good luck with the hackathon,

**Comment by co9olguy** [comment]
Thanks for your Power Up Submission @carlosamds !

To help us keep track of final submissions, we will be closing all of the [Power Up] issues. We ask you to open a new issue for your final submission. Please use [this pre-formatted [Entry] Issue template](https://github.com/XanaduAI/QHack/issues/new?assignees=&labels=submission&template=open-hackathon-final-submission.md&title=%5BENTRY%5D+Your+Project+Title). Note that for the final submission, the Resource Estimate requirement is replaced by a Presentation item.
